;	 0        1         2         3         4         5
;	"123456789012345678901234567890123456789012345678901"
VETA_NO_WAY:
defb	"YOU CAN'T GO THAT WAY.",0
VETA_NO_PUT:
defb	"YOU CANT PUT THAT ITEM THERE.",0

VETA_CASTS:
defb	"??? CASTS BLESS.",0
VETA_PRY_DOOR:
defb	"NO ONE IS ABLE TO PRY THIS DOOR OPEN.",0	; Nikdo neni schopen tyto dvere vypacit/zvednout.
VETA_FORCES:
defb	"THE PARTY FORCES THE DOOR.",0

VETA_TAKEN:
defb	" TAKEN.",0

VETA_PUT:
defb	" WAS PUT.",0

VETA_DRINK:
defb    " WAS DRUNK.",0

VETA_EAT:
defb    " WAS EATEN.",0



;	 0        1         2         3         4         5
;	"123456789012345678901234567890123456789012345678901"
; modrozeleny

ARRAY_STRING_DEKORACE:					; radi se podle podtypu TYP_DEKORACE
defb	"SOMETHING SCURRIES DEEPER INTO THE FLOOR DRAIN.",0
defb	"THIS RUNE IS UNRECOGNIZED.",0

ARRAY_STRING_PREPINACE:					; radi se podle podtypu TYP_PREPINAC
defb	"YOU SWITCHED THE LEVER.", 0
defb	"YOU PRESSED THE BUTTON.", 0
defb	"YOU PRESSED THE HIDE BUTTON.", 0
defb	"YOU SWITCHED THE LOCK.", 0

VETA_11:
defb	"THIS SLIMY, SMELLY DRAIN PIPE REVEALS NOTHING.",0
VETA_13:
defb	"THERE IS A DRAINAGE GRATE HERE.",0
VETA_14:
defb	"ONLY THE STRONG SHALL PASS.",0
VETA_15:
defb	"WATCH YOUR STEP.",0	; divej se kam slapes
VETA_16:
defb	"NOT ALL IS AS IT APPEARS",0	; nic neni takove jako se zda



; fialovy
VETA_EXP:
defb	"??? HAS GAINED A LEVEL OF EXPERIENCE.",0

; zluty
VETA_DOWN:
defb	"GOING DOWN...",0
VETA_UP:
defb	"GOING UP.",0
VETA_DOOR:
defb	"THE DOOR APPEARS STUCK.",0
VETA_DAGGER:
defb	"THE DAGGER FITS.",0
VETA_HOLLOW:
defb	"A HOLLOW LAUGHTER ECHOES FAINTLY.",0	; duty smich se rozleha

; cerveny
VETA_UNDEAD:
defb	"??? USES THE POWER TO TURN UNDEAD!",0


;	 0        1         2         3         4         5
;	"123456789012345678901234567890123456789012345678901"
HELP_STRING:
defb	"TEST ZX DUNGEON DEMO V 0.73",0
defb	"OVLADANI: ",KEY_DOLEVA-32,",",KEY_DOPRAVA-32,"-OTOCENI; ",KEY_DOPREDU-32,",",KEY_DOZADU-32,"-POHYB; ",KEY_VLEVO-32,",",KEY_VPRAVO-32,"-UKROK",0
defb	KEY_MINUS-32,",",KEY_PLUS-32,",1..6-AKTIVNI POSTAVA; ",KEY_INVENTAR-32,"-INVENTAR; ", KEY_FHAND-32,",",KEY_SHAND-32,"-HANDS",0
defb	"SPACE (MEZERNIK) - AKCE; SS+X (CTRL+X) - KONEC",0
NEXT_NAME	equ	11


VETA_HP:
defb	"HP",0

; pozpatku, kvuli vykresleni ve smycce
NAMES:
defb "DOHRUM    ",0
defb "WYRD      ",0
defb "LINDA     ",0
defb "EITHNE    ",0
defb "TOD UPHILL",0
defb "IRIS      ",0
NAMES_END:


ARRAY_STRING_ITEMS:
defb	"",0			; empty
;-----
defb	"RING",0
defb	"RUBIN RING",0
defb	"SMARAGD RING",0
defb	"SAPPHIRE RING",0
defb	"DIAMOND RING",0
;----- serazeno tak, aby se co nejlepe zjistovaly zakazane pozice pro dane predmety
defb	"HELM",0
defb	"DWARVEN HELM",0
defb	"NECKLACE",0
;--
defb	"ARMOR",0
defb	"CHAINMAIL",0
defb	"LEATHER ARMOR",0
defb	"PLATE ARMOR",0
  ;--
defb	"ARROW",0
defb	"BRACERS",0
defb	"BOOTS",0
;-----
defb	"ANKH",0
defb	"AXE",0
defb	"BOOK",0
defb	"BOW",0
defb	"DAGGER",0
defb	"MACE",0
defb	"SHIELD",0
defb	"SPIDER SHIELD",0
defb	"SLING",0
defb	"SWORD",0
defb	"BONE",0
;----- veci s hodnotou MIN_FOOD vcetne musi byt jedle
defb	"RATIONS",0
defb	"HEALING POTION",0
defb	"ANTIDOTE POTION",0
defb	"POTION_B",0

; RATIONS, CLERIC HOLY SYMBOL, LOCK PICKS, SHORT SWORD, HALFLING BONES
; SILVER KEY, IRON RATIONS, POTION, POTION OF GIANT STRENGTH, POTION OF HEALING
; ARROW, SLING, STONE DAGGER
; MAGE SCROLL OF DETECT MAGIC
; MAGE SCROLL OF ARMOR
; CLERIC SCROLL OF BLESS
